import { Category, MenuItem } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: '1', slug: 'all', name_ar: 'جميع الأطباق', name_en: 'All Items', sort_order: 0, is_active: true },
  { id: '2', slug: 'small-plates', name_ar: 'أطباق صغيرة ومقبلات', name_en: 'Small Plates & Mezze', sort_order: 1, is_active: true },
  { id: '3', slug: 'mains', name_ar: 'الأطباق الرئيسية', name_en: 'Hearth & Mains', sort_order: 2, is_active: true },
  { id: '4', slug: 'flatbreads', name_ar: 'مناقيش ومعجنات', name_en: 'Artisan Flatbreads', sort_order: 3, is_active: true },
  { id: '5', slug: 'sweets', name_ar: 'حلويات', name_en: 'Artisan Sweets', sort_order: 4, is_active: true },
  { id: '6', slug: 'drinks', name_ar: 'مشروبات وعصائر', name_en: 'Drinks & Elixirs', sort_order: 5, is_active: true },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Small Plates
  {
    id: 'sp-1',
    title: 'باذنجان مدخن بطحينة الرمان',
    category_slug: 'small-plates',
    price: 35000,
    tags: ['vg', 'gf', 'chef'],
    description: 'باذنجان مشوي على الحطب مهروس مع طحينة السمسم الخالصة، زيت الزعتر البري وحبات الرمان الطازجة.',
    ingredients: 'باذنجان مشوي، طحينة سمسم فاخرة، ثوم، زيت زيتون معتق، رمان، زعتر بري.',
    pairing: 'شراب الكركديه والنعناع الفوار',
    image_url: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=700&q=80',
    badge: 'طبق توقيع',
    is_available: true,
    is_featured: true,
    sort_order: 1
  },
  {
    id: 'sp-2',
    title: 'شمندر مشوي بحطب اللوز مع الدقة',
    category_slug: 'small-plates',
    price: 38000,
    tags: ['v', 'gf'],
    description: 'شرائح الشمندر الأحمر والذهبي المخبوزة بطبطبة هادئة، مع لبنة الغنم المخفوقة ودقة البندق المصرية.',
    ingredients: 'شمندر طازج، لبنة بلدية مخفوقة، دقة بندق محمصة، برك بشر البرتقال.',
    pairing: 'موكتيل الورد والليمون',
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80',
    badge: null,
    is_available: true,
    is_featured: true,
    sort_order: 2
  },
  {
    id: 'sp-3',
    title: 'حلوم مقرمش بعسل العنبر',
    category_slug: 'small-plates',
    price: 42000,
    tags: ['v', 'chef'],
    description: 'جبن حلوم مشوي ومقرمش بلمسة عسل الجبال الجبلي، أوراق أوريغانو طازجة وفلفل أحمر مجفف.',
    ingredients: 'جبن حلوم قبرصي، عسل جبال الجولان، أوريغانو طازج، رقائق فلفل أحمر.',
    pairing: 'مشروب الزعفران البارد',
    image_url: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=700&q=80',
    badge: 'الأكثر طلباً',
    is_available: true,
    is_featured: false,
    sort_order: 3
  },
  {
    id: 'sp-4',
    title: 'أخطبوط مشوي بكريم البطاطا بالزعفران',
    category_slug: 'small-plates',
    price: 65000,
    tags: ['gf'],
    description: 'مجسات أخطبوط طرية ومشوية على الحطب تُقدم فوق بيوريه البطاطا المخملية المعطرة بالزعفران.',
    ingredients: 'أخطبوط بحري، زعفران حر، بطاطا يوكون، زيت زيتون بكر، كبر، ليمون.',
    pairing: 'مشروب غروب العنبر',
    image_url: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=700&q=80',
    badge: null,
    is_available: true,
    is_featured: false,
    sort_order: 4
  },
  {
    id: 'sp-5',
    title: 'حمص ملكي بزيت الكمأة البرية',
    category_slug: 'small-plates',
    price: 32000,
    tags: ['vg'],
    description: 'حمص عضوي ناعم ومخفوق بعناية، مع قطرات زيت الكمأة البيضاء وشرائح الخبز الحجري الساخن.',
    ingredients: 'حمص عضوي، زيت الكمأة البيضاء، طحينة، بابريكا مدخنة، خبز صاج ساخن.',
    pairing: 'مياه معدنية فوارة',
    image_url: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=700&q=80',
    badge: null,
    is_available: true,
    is_featured: false,
    sort_order: 5
  },

  // Mains
  {
    id: 'm-1',
    title: 'موزة غنم مطهوة بالفرن الحجري',
    category_slug: 'mains',
    price: 95000,
    tags: ['gf', 'chef'],
    description: 'موزة غنم بلدية مطهوة بطريقة الطهي البطئ لمدة 8 ساعات مع صوص دبس الرمان وأرز الزعفران.',
    ingredients: 'لحم غنم بلدي، دبس رمان طبيعي، هيل، قرفة، أرز بسمتي بالزعفران.',
    pairing: 'مشروب غروب العنبر الخاص',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=700&q=80',
    badge: 'توصية الشيف',
    is_available: true,
    is_featured: true,
    sort_order: 6
  },
  {
    id: 'm-2',
    title: 'سمك سي باس بزبادي السماق المحمص',
    category_slug: 'mains',
    price: 88000,
    tags: ['gf'],
    description: 'فيليه سمك سي باس طازج مقرمش الجلد، يُقدم فوق ريزوتو الفريكة الخضراء وزبدة السماق البري.',
    ingredients: 'سمك سي باس بحري، زبدة محروقة، سماق بري، فريكة خضراء، ليمون مشوي.',
    pairing: 'شاي الأعشاب والحمضيات',
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=700&q=80',
    badge: null,
    is_available: true,
    is_featured: false,
    sort_order: 7
  },
  {
    id: 'm-3',
    title: 'ستيك زهرة (قرنابيط) مشوي بالحطب',
    category_slug: 'mains',
    price: 55000,
    tags: ['vg', 'gf'],
    description: 'شريحة زهرة كاملة محمصة بالفرن الحجري تُقدم على كريم الفستق الحلبي والطحينة مع بصل مخلل.',
    ingredients: 'قرنابيط كامل، كريم الفستق الحلبي والطحينة، بصل سماق مخلل، زيت بقدونس.',
    pairing: 'موكتيل الورد والليمون الفوار',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=700&q=80',
    badge: null,
    is_available: true,
    is_featured: false,
    sort_order: 8
  },
  {
    id: 'm-4',
    title: 'ريب آي ببهارات عنبر الخاصة (10 أونصة)',
    category_slug: 'mains',
    price: 120000,
    tags: ['gf'],
    description: 'شريحة ريب آي معتقة ومتبلة بخلطة الكزبرة والكمون والفلفل الأسود، تُقدم مع كراث مشوي.',
    ingredients: 'لحم ريب آي أنغوس، بهارات عنبر الخاصة، كراث مشوي، زبدة الثوم والبهارات.',
    pairing: 'غروب العنبر',
    image_url: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=700&q=80',
    badge: null,
    is_available: true,
    is_featured: false,
    sort_order: 9
  },

  // Flatbreads
  {
    id: 'fb-1',
    title: 'مناقيش الفطر البري وجبن الماعز',
    category_slug: 'flatbreads',
    price: 45000,
    tags: ['v'],
    description: 'عجينة تخمير طبيعي مخبوزة على الحجر مع فطر الشانتريل المكون وموس جبن الماعز وزيت الترفل.',
    ingredients: 'عجين مخمر، فطر بري، جبن ماعز معتق، زعتر طازج، عسل الترفل.',
    pairing: 'مشروب القهوة الباردة',
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80',
    badge: null,
    is_available: true,
    is_featured: false,
    sort_order: 10
  },
  {
    id: 'fb-2',
    title: 'صفيحة لحم بالصنوبر ودبس الرمان',
    category_slug: 'flatbreads',
    price: 48000,
    tags: ['chef'],
    description: 'مناقيش لحم بلدي مفروم ومتبل بالبهارات الشرقية والصنوبر المحمص مع قطرات اللبنة والنعناع.',
    ingredients: 'لحم غنم مفروم، صنوبر، بهارات مشكلة، لبنة بالنعناع، دبس رمان.',
    pairing: 'شراب الكركديه الفوار',
    image_url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=700&q=80',
    badge: 'المفضلة في الدار',
    is_available: true,
    is_featured: false,
    sort_order: 11
  },
  {
    id: 'fb-3',
    title: 'مناقيش زعتر بري وزيت زيتون معتق',
    category_slug: 'flatbreads',
    price: 25000,
    tags: ['vg'],
    description: 'مناقيش هشة ومقرمشة مع الزعتر البري الجبلي والسمسم الأبيض المحمص وزيت الزيتون البكر.',
    ingredients: 'زعتر بري، سمسم محمص، زيت زيتون بكر ممتاز، ملح بحري.',
    pairing: 'شاي بالنعناع',
    image_url: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=700&q=80',
    badge: null,
    is_available: true,
    is_featured: false,
    sort_order: 12
  },

  // Sweets
  {
    id: 'sw-1',
    title: 'كيكة الحليب بالهيل وماء الزهر',
    category_slug: 'sweets',
    price: 30000,
    tags: ['v', 'chef'],
    description: 'كيكة إسفنجية خفيفة مشربة بصلصة الحليب الثلاثية المعطرة بالهيل وماء الزهر مع فستق حلبي.',
    ingredients: 'حليب عضوي، هيل أخضر، ماء زهر طبيعي، فستق حلبي، كيك إسفنجي.',
    pairing: 'إسبريسو بالهيل',
    image_url: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=700&q=80',
    badge: 'تجربة ممتازة',
    is_available: true,
    is_featured: false,
    sort_order: 13
  },
  {
    id: 'sw-2',
    title: 'تارت التين المشوي وعسل العنبر',
    category_slug: 'sweets',
    price: 32000,
    tags: ['v'],
    description: 'عجينة لوز هشة محشوة بكراميل الماسكاربوني مع تين طازج مشوي وعسل اللافندر.',
    ingredients: 'تين طازج، جبن ماسكاربوني، عسل اللافندر، عجينة زبدة باللوز.',
    pairing: 'موكتيل الورد',
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=700&q=80',
    badge: null,
    is_available: true,
    is_featured: false,
    sort_order: 14
  },
  {
    id: 'sw-3',
    title: 'غاناش الشوكولاتة الداكنة بزيت الزيتون',
    category_slug: 'sweets',
    price: 35000,
    tags: ['v', 'gf'],
    description: 'غاناش شوكولاتة داكنة 70% مخفوقة مع زيت زيتون ناعم ورقائق الملح البحري.',
    ingredients: 'شوكولاتة داكنة 70%، زيت زيتون بكر، رقائق ملح البحر، حبيبات الكاكاو.',
    pairing: 'شاي أسود معطر بالبهارات',
    image_url: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=700&q=80',
    badge: null,
    is_available: true,
    is_featured: false,
    sort_order: 15
  },

  // Drinks
  {
    id: 'dr-1',
    title: 'شراب غروب العنبر الخاص',
    category_slug: 'drinks',
    price: 38000,
    tags: ['chef'],
    description: 'مشروب مبتكر مستخلص من التمر المدخن، مرارات البرتقال، وإكليل الجبل المشتعل يُقدم فوق كرة ثلجية.',
    ingredients: 'خلاصة تمر مدخن، مرارات البرتقال، روزماري مشوي، مياه فوارة.',
    pairing: 'مثالي مع الأطباق الرئيسية',
    image_url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=700&q=80',
    badge: 'مشروب عنبر',
    is_available: true,
    is_featured: false,
    sort_order: 16
  },
  {
    id: 'dr-2',
    title: 'موكتيل الورد والليمون الفوار',
    category_slug: 'drinks',
    price: 28000,
    tags: ['vg', 'gf'],
    description: 'ماء ورد جوري طبيعي، عصير الليتشي الطازج، شاي أبيض فوار مع بشر الليمون.',
    ingredients: 'ماء ورد جوري، ليتشي طازج، شاي أبيض، مياه فوارة، نعناع.',
    pairing: 'يناسب المقبلات والشمندر',
    image_url: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=700&q=80',
    badge: null,
    is_available: true,
    is_featured: false,
    sort_order: 17
  },
  {
    id: 'dr-3',
    title: 'قهوة باردة بالزعفران للهيل',
    category_slug: 'drinks',
    price: 22000,
    tags: ['v', 'gf'],
    description: 'قهوة أرابيكا مقطرة ببطء ومنقوعة بخيوط الزعفران والهيل الأخضر مع رغوة حليب الشوفان.',
    ingredients: 'قهوة أرابيكا، زعفران، هيل، حليب شوفان.',
    pairing: 'يناسب كيكة الحليب',
    image_url: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=700&q=80',
    badge: null,
    is_available: true,
    is_featured: false,
    sort_order: 18
  }
];
