-- ==============================================================================
-- ANBAR RESTAURANT - COMPLETE INITIAL SEED DATA
-- ==============================================================================
-- Generated from Restaurant Menu.md for Supabase SQL Editor

-- 1. SEED CATEGORIES
INSERT INTO public.categories (slug, name_ar, name_en, sort_order, is_active) VALUES
('all', 'جميع الأصناف', 'All Items', 0, true),
('hot-drinks', 'المشروبات الساخنة', 'Hot Drinks', 1, true),
('latte', 'لاتيه', 'Latte', 2, true),
('fresh-juices', 'عصاير فريش', 'Fresh Juices', 3, true),
('cold-mixes', 'خلطات باردة', 'Cold Mixes', 4, true),
('smoothies', 'سموزيات', 'Smoothies', 5, true),
('soft-drinks', 'المشروبات الغازية', 'Soft Drinks & Extras', 6, true),
('milkshake', 'ميلك شيك', 'Milkshake', 7, true),
('cocktails', 'كوكتيلات', 'Cocktails', 8, true),
('ice-cream', 'بوظة', 'Ice Cream', 9, true),
('crepe', 'كريب', 'Crepe', 10, true),
('special-sweets', 'سبيشال سويت', 'Special Sweets', 11, true),
('dessert-salads', 'السلطات - حلويات', 'Dessert Salads', 12, true),
('salads', 'السلطات', 'Salads', 13, true),
('sandwiches', 'صندويش', 'Sandwiches', 14, true),
('beef', 'عجل', 'Veal & Beef', 15, true),
('appetizers', 'المقبلات', 'Appetizers', 16, true),
('pasta', 'باستا', 'Pasta', 17, true),
('plomi', 'بلوميات', 'Plomi Dishes', 18, true),
('burgers', 'برغر', 'Burgers', 19, true),
('pizza', 'بيتزا', 'Pizza', 20, true),
('family-meals', 'وجبات عائلي', 'Family Meals', 21, true),
('main-meals', 'الوجبات الرئيسية', 'Main Meals', 22, true)
ON CONFLICT (slug) DO UPDATE SET
    name_ar = EXCLUDED.name_ar,
    name_en = EXCLUDED.name_en,
    sort_order = EXCLUDED.sort_order,
    is_active = EXCLUDED.is_active;

-- 2. SEED MENU ITEMS
INSERT INTO public.menu_items (id, title, category_slug, price, description, ingredients, pairing, image_url, badge, tags, is_available, is_featured, sort_order) VALUES

-- -----------------------------------------------------------------------------
-- ☕ 1. المشروبات الساخنة (Hot Drinks)
-- -----------------------------------------------------------------------------
('hd-1', 'هوت شوكليت (Hot Chocolate)', 'hot-drinks', 300, 'شوكولاتة ساخنة غنية ومخملية مع رغوة الحليب الطازج.', 'شوكولاتة داكنة فاخرة، حليب طازج، فانيليا، كريمة مخفوقة.', 'كوكيز أو براونيز', 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=700&q=80', 'شائع', ARRAY['v'], true, false, 1),
('hd-2', 'زهورات (Herbal Tea)', 'hot-drinks', 150, 'مزيج عطري مهدئ من الزهورات والأعشاب الطبيعية الشامية.', 'بابونج، ورد جوري، زعتر بري، يانسون، مليسة.', 'عسل طبيعي', 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 2),
('hd-3', 'شاي بأنواعه (Tea all kinds)', 'hot-drinks', 150, 'شاي أسود وأخضر وأعشاب فاخر مخمر على الأصول.', 'أوراق شاي مختارة، نعناع طازج، هيل (حسب الرغبة).', 'بسكويت خفيف', 'https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 3),
('hd-4', 'مكياتو (Macchiato)', 'hot-drinks', 300, 'جرعة إسبريسو قوية مع لمسة ناعمة من رغوة الحليب المخملية.', 'بن أرابيكا محمص، رغوة حليب مبخر.', 'تيراميسو', 'https://images.unsplash.com/photo-1557006021-b85faa2bc5e2?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 4),
('hd-5', 'قهوة شرقية (Oriental Coffee)', 'hot-drinks', 150, 'قهوة عربية أصيلة معتقة ومحضرة مع الهيل الفاخر.', 'بن تركي/عربي محمص، هيل أخضر مطحون، ماء نقي.', 'تمر محشو', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=700&q=80', 'أصالة الدار', ARRAY['vg', 'gf'], true, false, 5),
('hd-6', 'إسبريسو (Espresso)', 'hot-drinks', 150, 'خلاصة قهوة مركزة بنكهة غنية وكريما ذهبية داكنة.', 'بن إسبريسو إيطالي 100% أرابيكا.', 'كوب ماء فوار', 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 6),
('hd-7', 'إسبريسو سنيكرز (Espresso Snickers)', 'hot-drinks', 200, 'إسبريسو مميز بنكهة شوكولاتة وفول سوداني وكراميل سنيكرز.', 'إسبريسو، صوص سنيكرز، فول سوداني، كراميل.', 'وافل', 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=700&q=80', 'مميز', ARRAY['v'], true, false, 7),
('hd-8', 'إسبريسو كوفيانا (Espresso Coffiana)', 'hot-drinks', 200, 'إسبريسو بنكهة كوفيانا الغنية والمبتكرة.', 'إسبريسو محمص، خلطة كوفيانا الخاصة.', 'كيكة رول', 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 8),
('hd-9', 'إسبريسو كوكيز (Espresso Cookies)', 'hot-drinks', 200, 'إسبريسو دافئ ممتزج بفتات ونكهة الكوكيز المقرمشة.', 'إسبريسو، نكهة كوكيز بالشوكولاتة، حليب خفيف.', 'كوكيز كلاسيك', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 9),
('hd-10', 'إسبريسو مكياتو (Espresso Macchiato)', 'hot-drinks', 200, 'شوت إسبريسو مضاعف مع قطرة كريمة الحليب.', 'إسبريسو غامق، حليب مكثف ومبخر.', 'قطعة شوكولاتة', 'https://images.unsplash.com/photo-1557006021-b85faa2bc5e2?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 10),
('hd-11', 'نسكافيه بلاك (Nescafe Black)', 'hot-drinks', 150, 'قهوة سريعة التحضير نقية ومركزة.', 'حبوب نسكافيه كلاسيك نقية.', 'شوكولاتة داكنة', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 11),
('hd-12', 'نسكافيه بلاك مع حليب (Nescafe Black with Milk)', 'hot-drinks', 250, 'نسكافيه متوازن ممزوج بالحليب الطازج الساخن.', 'نسكافيه، حليب ساخن كامل الدسم.', 'كرواسون', 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 12),
('hd-13', '٣ ب ١ (3 in 1)', 'hot-drinks', 250, 'مزيج قهوة بالحليب مع السكر المتوازن.', 'قهوة سريعة، مبيض حليب، سكر نقي.', 'بسكويت', 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 13),
('hd-14', '٢ ب ١ (2 in 1)', 'hot-drinks', 250, 'مزيج قهوة مع الحليب بدون سكر مضاف.', 'قهوة سريعة، مبيض حليب.', 'تمر', 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 14),
('hd-15', 'ميلو (Milo)', 'hot-drinks', 200, 'مشروب الشوكولاتة والشعير المغذي الساخن.', 'بودرة ميلو بالشوكولاتة والشعير، ماء ساخن.', 'توست محمص', 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 15),
('hd-16', 'ميلو مع حليب (Milo with Milk)', 'hot-drinks', 250, 'ميلو كريمي غني بالحليب الطازج الساخن.', 'ميلو، حليب طازج مغلي، رغوة شوكولاتة.', 'براونيز', 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=700&q=80', 'المفضل', ARRAY['v'], true, false, 16),

-- -----------------------------------------------------------------------------
-- ☕ 2. لاتيه (Latte)
-- -----------------------------------------------------------------------------
('lat-1', 'كابتشينو (Cappuccino)', 'latte', 250, 'إسبريسو متوازن مع طبقة سميكة من رغوة الحليب ورشة كاكاو.', 'إسبريسو، حليب مبخر، رغوة حليب كثيفة، بودرة كاكاو.', 'كرواسون زبدة', 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=700&q=80', 'كلاسيك', ARRAY['v'], true, false, 17),
('lat-2', 'موكاشينو (Mocaccino)', 'latte', 300, 'مزيج ساحر من الإسبريسو والشوكولاتة الذائبة مع الحليب.', 'إسبريسو، صوص شوكولاتة بلجيكية، حليب مبخر، كريمة.', 'كيك الشوكولاتة', 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 18),
('lat-3', 'وايت لاتيه (White Latte)', 'latte', 300, 'لاتيه فاخر بنكهة الشوكولاتة البيضاء السلسة.', 'إسبريسو، شوكولاتة بيضاء، حليب مبخر ناعم.', 'تارت فواكه', 'https://images.unsplash.com/photo-1529892485617-25f63cd7b1e9?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 19),
('lat-4', 'بيستاشيو لاتيه (Pistachio Latte)', 'latte', 300, 'إسبريسو ممزوج بكريمة الفستق الحلبي الطبيعية ورغوة الحليب.', 'إسبريسو، معجون فستق حلبي، حليب مبخر، فستق مجروش.', 'كريب فستق', 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=700&q=80', 'الأكثر طلباً', ARRAY['v'], true, true, 20),
('lat-5', 'كراميل مكياتو (Caramel Macchiato)', 'latte', 300, 'حليب مبخر بنكهة الفانيليا يعلوه شوت إسبريسو وخطوط الكراميل الذهبي.', 'إسبريسو، حليب مبخر، سيروب فانيليا، صوص كراميل.', 'وافل كراميل', 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 21),
('lat-6', 'سبانيش لاتيه (Spanish Latte)', 'latte', 300, 'لاتيه إسباني مميز بنعومة الحليب المكثف المحلى ونكهة القهوة.', 'إسبريسو مضاعف، حليب مكثف محلى، حليب طازج مبخر.', 'تشيز كيك', 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=700&q=80', 'توصية البارستا', ARRAY['v'], true, true, 22),

-- -----------------------------------------------------------------------------
-- 🍊 3. عصاير فريش (Fresh Juices)
-- -----------------------------------------------------------------------------
('fj-1', 'عصير برتقال فريش (Fresh Orange Juice)', 'fresh-juices', 300, 'عصير برتقال طبيعي 100% معصور طازجاً عند الطلب.', 'برتقال بلدي طازج معصور.', 'سلطة فواكه', 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=700&q=80', 'طازج يومياً', ARRAY['vg', 'gf'], true, false, 23),
('fj-2', 'عصير كيوي فريش (Fresh Kiwi Juice)', 'fresh-juices', 300, 'عصير كيوي منعش غني بفيتامين C والنكهة الاستوائية.', 'كيوي طازج، ثلج مجروش، عسل خفيف.', 'مقبلات باردة', 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 24),
('fj-3', 'عصير فريز فريش (Fresh Strawberry Juice)', 'fresh-juices', 300, 'عصير فراولة طبيعية طازجة وباردة.', 'فراولة طازجة، ثلج، لمسة ليمون.', 'كريب شوكولاتة', 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 25),
('fj-4', 'عصير رمان فريش (Fresh Pomegranate Juice)', 'fresh-juices', 300, 'عصير رمان طبيعي بلدي غني ومضاد للأكسدة.', 'حبات رمان طبيعية 100%.', 'مشاوي وسندويش', 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=700&q=80', 'صحي', ARRAY['vg', 'gf'], true, false, 26),
('fj-5', 'عصير أناناس فريش (Fresh Pineapple Juice)', 'fresh-juices', 300, 'عصير أناناس استوائي بارد ومنعش.', 'أناناس طازج، ثلج.', 'برغر أو زنجر', 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 27),
('fj-6', 'عصير تفاح فريش (Fresh Apple Juice)', 'fresh-juices', 300, 'عصير تفاح طبيعي معصور طازجاً وبارداً.', 'تفاح أحمر وأخضر طازج.', 'سلطة سيزر', 'https://images.unsplash.com/photo-1568644396922-5c3bfae12521?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 28),
('fj-7', 'عصير مانغو فريش (Fresh Mango Juice)', 'fresh-juices', 300, 'عصير مانجو استوائي كثيف وطبيعي بمذاق حلو فاخر.', 'مانجو طبيعي طازج، ثلج مجروش.', 'كريب نوتيلا', 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=700&q=80', 'مميز', ARRAY['vg', 'gf'], true, true, 29),

-- -----------------------------------------------------------------------------
-- ❄️ 4. خلطات باردة (Cold Mixes)
-- -----------------------------------------------------------------------------
('cm-1', 'فرابيه ليمون (Lemon Frappe)', 'cold-mixes', 400, 'فرابيه الليمون المنعش المخفوق بالثلج والنعناع الأخضر.', 'ليمون طازج، نعناع، ثلج مجروش، سيروب محلى.', 'وجبات الدجاج والباستا', 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=700&q=80', 'انتعاش خالص', ARRAY['vg', 'gf'], true, false, 30),
('cm-2', 'غولدن كافيه (Golden Cafe)', 'cold-mixes', 300, 'خلطة القهوة الذهبية الباردة مع رغوة غنية ولمسات خاصة.', 'إسبريسو بارد، حليب، خلطة غولدن الخاصة.', 'كيكة التيراميسو', 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 31),
('cm-3', 'آيس تي فريش (Fresh Iced Tea)', 'cold-mixes', 350, 'شاي مثلج طازج مع شرائح الليمون والخوخ والنعناع.', 'شاي مخمر مبرد، خوخ، ليمون، نعناع، ثلج.', 'صندويشات ومقبلات', 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 32),
('cm-4', 'آيس كافيه (Iced Cafe)', 'cold-mixes', 350, 'قهوة مثلجة منعشة محضرة من الإسبريسو المركز والحليب البارد.', 'إسبريسو مزدوج، حليب مثلج، مكعبات ثلج.', 'كوكيز أو دونات', 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 33),
('cm-5', 'موهيتو (Mojito)', 'cold-mixes', 350, 'موهيتو كلاسيكي منعش بالليمون والنعناع والمياه الفوارة.', 'مياه فوارة، ليمون أخضر، أوراق نعناع، سكر قصب، ثلج.', 'بيتزا وبرغر', 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=700&q=80', 'الأكثر مبيعاً', ARRAY['vg', 'gf'], true, true, 34),
('cm-6', 'غرين بلو (Green Blue)', 'cold-mixes', 350, 'مشروب المحيط الأزرق مع لمسات الحمضيات والنعناع الأخضر.', 'بلو كوراساو، صودا ليمون، نعناع، ثلج مجروش.', 'مقبلات وسناكات', 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=700&q=80', 'مميز', ARRAY['vg', 'gf'], true, false, 35),

-- -----------------------------------------------------------------------------
-- 🍓 5. سموزيات (Smoothies)
-- -----------------------------------------------------------------------------
('sm-1', 'سموذي تفاح (Apple Smoothie)', 'smoothies', 300, 'سموذي تفاح منعش مخفوق بالثلج والعسل الطبيعي.', 'تفاح طازج، ثلج مجروش، عسل.', 'سناك صحي', 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 36),
('sm-2', 'سموذي كرز (Cherry Smoothie)', 'smoothies', 300, 'سموذي كرز طبيعي بنكهة غنية منعشة وحموضة لطيفة.', 'كرز طازج، ثلج، ماء زهر خفيف.', 'تشيز كيك', 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 37),
('sm-3', 'سموذي برتقال (Orange Smoothie)', 'smoothies', 300, 'سموذي برتقال بارد ومخفوق بالثلج.', 'برتقال، ثلج مجروش، لمسة فانيليا.', 'كرواسون', 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 38),
('sm-4', 'سموذي أناناس (Pineapple Smoothie)', 'smoothies', 300, 'سموذي أناناس استوائي بارد ومخملي.', 'أناناس، ثلج، حليب جوز هند خفيف.', 'سلطات', 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 39),
('sm-5', 'سموذي مانغو (Mango Smoothie)', 'smoothies', 300, 'سموذي مانجو غني وكثيف مع الثلج المجروش.', 'مانجو استوائي، ثلج، عسل.', 'كريب وسويت', 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=700&q=80', 'مميز', ARRAY['vg', 'gf'], true, false, 40),
('sm-6', 'سموذي فريز (Strawberry Smoothie)', 'smoothies', 300, 'سموذي فراولة طازجة مخفوقة بطعم غني ومحبوب.', 'فراولة طازجة، ثلج، لمسة عسل.', 'وافل', 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=700&q=80', 'مفضل', ARRAY['vg', 'gf'], true, false, 41),

-- -----------------------------------------------------------------------------
-- 🥤 6. المشروبات الغازية والإضافات (Soft Drinks & Extras)
-- -----------------------------------------------------------------------------
('sd-1', 'بيبسي تنك (Pepsi Can)', 'soft-drinks', 150, 'مشروب بيبسي غازي منعش في عبوة معدنية باردة.', 'بيبسي كولا، غازات منعشة.', 'البرغر والبيتزا', 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 42),
('sd-2', 'بيبسي رياضي (Pepsi Sport)', 'soft-drinks', 100, 'مشروب غازي منعش بحجم رياضي عملي.', 'بيبسي رياضي.', 'وجبات خفيفة', 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 43),
('sd-3', 'بيبسي لتر (Pepsi Liter)', 'soft-drinks', 200, 'عبوة بيبسي بحجم 1 لتر تكفي للمشاركة.', 'بيبسي كولا 1 لتر.', 'الوجبات العائلية والبيتزا', 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 44),
('sd-4', 'بيبسي عائلي (Pepsi Family size)', 'soft-drinks', 350, 'عبوة بيبسي عائلية كبيرة للمناسبات والجمعات.', 'بيبسي كولا حجم عائلي كبير.', 'الأطباق العائلية والوجبات', 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 45),
('sd-5', 'عيران (Ayran)', 'soft-drinks', 70, 'لبن عيران بلدي طازج مملح ومخفوق بالنعناع.', 'لبن زبادي بلدي، ماء نقي، ملح، نعناع.', 'المشاوي والسندويش', 'https://images.unsplash.com/photo-1571212515416-fef01fc43637?auto=format&fit=crop&w=700&q=80', 'صحي وبلدي', ARRAY['v', 'gf'], true, false, 46),
('sd-6', 'مياه كبيرة (Large Water)', 'soft-drinks', 125, 'عبوة مياه معدنية طبيعية نقية بحجم كبير (1.5 لتر).', 'مياه معدنية طبيعية.', 'جميع الوجبات', 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 47),
('sd-7', 'مياه صغيرة (Small Water)', 'soft-drinks', 50, 'عبوة مياه معدنية نقية صغيرة شخصية.', 'مياه معدنية طبيعية.', 'جميع الوجبات', 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 48),
('sd-8', 'أركيلة عنبر (Hookah)', 'soft-drinks', 240, 'أركيلة فاخرة بنكهات معسل مميزة وفحم طبيعي مشتعل.', 'معسل فاخر (تفاحتين، عنب ونعناع، خلطة عنبر)، فحم طبيعي.', 'شاي ساخن أو موهيتو', 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=700&q=80', 'جلسات الدار', ARRAY['v'], true, false, 49),

-- -----------------------------------------------------------------------------
-- 🍧 7. ميلك شيك (Milkshake)
-- -----------------------------------------------------------------------------
('ms-1', 'ميلك شيك بيستاشيو (Pistachio Milkshake)', 'milkshake', 350, 'ميلك شيك كريمي غني بالفستق الحلبي الطبيعي والآيس كريم.', 'آيس كريم فستق، حليب مثلج، معجون فستق، كريمة مخفوقة.', 'كريب فستق', 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=700&q=80', 'مميز', ARRAY['v'], true, false, 50),
('ms-2', 'ميلك شيك أوريو (Oreo Milkshake)', 'milkshake', 350, 'ميلك شيك شوكولاتة وفانيليا مع بسكويت أوريو المطحون.', 'بسكويت أوريو، آيس كريم فانيليا، حليب، صوص شوكولاتة.', 'براونيز', 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=700&q=80', 'الأكثر طلباً', ARRAY['v'], true, true, 51),
('ms-3', 'ميلك شيك شوكولا (Chocolate Milkshake)', 'milkshake', 350, 'ميلك شيك شوكولاتة بلجيكية غنية مع الكريمة المخفوقة.', 'آيس كريم شوكولاتة، حليب، صوص كاكاو.', 'فوندون', 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 52),
('ms-4', 'ميلك شيك فريز (Strawberry Milkshake)', 'milkshake', 350, 'ميلك شيك فراولة طبيعية ناعمة مع صوص الفريز.', 'آيس كريم فراولة، حليب، فراولة طازجة، كريمة.', 'وافل فواكه', 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 53),
('ms-5', 'ميلك شيك فانيلا (Vanilla Milkshake)', 'milkshake', 350, 'ميلك شيك فانيليا مدغشقر الكلاسيكي الناعم.', 'آيس كريم فانيليا، حليب كامل الدسم، كريمة مخفوقة.', 'كوكيز', 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 54),
('ms-6', 'ميلك شيك تشيز كيك (Cheesecake Milkshake)', 'milkshake', 350, 'مزيج فاخر من نكهة التشيز كيك الغنية مع الحليب والبسكويت.', 'جبن كريمي، بسكويت دايجستف، آيس كريم، صوص توت.', 'تيراميسو', 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=700&q=80', 'تجربة فريدة', ARRAY['v'], true, false, 55),
('ms-7', 'ميلك شيك كوكيز (Cookies Milkshake)', 'milkshake', 350, 'ميلك شيك شهي بقطع وحبيبات الكوكيز اللذيذة.', 'كوكيز شوكولاتة، آيس كريم، حليب، صوص كراميل.', 'وافل شوكولا', 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 56),
('ms-8', 'ميلك شيك لوتس (Lotus Milkshake)', 'milkshake', 350, 'ميلك شيك غني بزبدة وبسكويت اللوتس المقرمش.', 'بسكويت لوتس، زبدة لوتس، آيس كريم فانيليا، حليب.', 'كريب لوتس', 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=700&q=80', 'مميز جداً', ARRAY['v'], true, false, 57),

-- -----------------------------------------------------------------------------
-- 🍸 8. كوكتيلات (Cocktails)
-- -----------------------------------------------------------------------------
('ck-1', 'كوكتيل عنبر الخاص (Anbar Cocktail)', 'cocktails', 400, 'كوكتيل الدار الفاخر من الفواكه الاستوائية والمكسرات والقشطة.', 'قطع فواكه موسمية، عصير مانجو وفريز، قشطة، عسل، مكسرات.', 'كريب عنبر', 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=700&q=80', 'توقيع عنبر', ARRAY['v'], true, true, 58),
('ck-2', 'كوكتيل نوتيلا (Nutella Cocktail)', 'cocktails', 400, 'كوكتيل غني بشوكولاتة نوتيلا والبندق المحمص والحليب.', 'نوتيلا أصلية، حليب مثلج، آيس كريم شوكولاتة، بندق.', 'وافل', 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 59),
('ck-3', 'كوكتيل حليب (Milk Cocktail)', 'cocktails', 400, 'كوكتيل حليب طازج مخفوق مع الموز والفواكه والمكسرات.', 'حليب طازج، موز، عسل جبلي، مكسرات مشكلة.', 'سلطة فواكه', 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v', 'gf'], true, false, 60),
('ck-4', 'كوكتيل فواكه (Fruits Cocktail)', 'cocktails', 400, 'طبقات متعددة من عصائر الفواكه الطبيعية الطازجة مع قطع الفواكه.', 'طبقات مانجو، فريز، أفوكادو أو كيوي، قطع فواكه طازجة.', 'كيك كلاس', 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=700&q=80', 'طبيعي 100%', ARRAY['v', 'gf'], true, false, 61),
('ck-5', 'كوكتيل فرولاتنو (Frolatno Cocktail)', 'cocktails', 400, 'كوكتيل مبتكر بنكهات التوت والفراولة واللاتيه البارد.', 'فراولة، توت بري، رغوة حليب مثلجة، سيروب مميز.', 'تارت فواكه', 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=700&q=80', 'مبتكر', ARRAY['v'], true, false, 62),

-- -----------------------------------------------------------------------------
-- 🍨 9. بوظة (Ice Cream)
-- -----------------------------------------------------------------------------
('ic-1', 'شوكولا مع عنبر (Chocolate with Anbar Ice Cream)', 'ice-cream', 400, 'آيس كريم شوكولاتة داكنة مع صوص ومكسرات عنبر الخاصة.', 'آيس كريم شوكولاتة، صوص عنبر، فستق، مكسرات محمصة.', 'براونيز', 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=700&q=80', 'فاخر', ARRAY['v'], true, false, 63),
('ic-2', 'بوظة كيندر (Kinder Ice Cream)', 'ice-cream', 350, 'آيس كريم ناعم بنكهة شوكولاتة وحليب كيندر الغنية.', 'آيس كريم كيندر، صوص شوكولاتة بيضاء وبنية، أصابع كيندر.', 'كريب كيندر', 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=700&q=80', 'محبوب', ARRAY['v'], true, false, 64),
('ic-3', 'بوظة سنيكرز (Snickers Ice Cream)', 'ice-cream', 350, 'آيس كريم كراميل وفول سوداني وشوكولاتة سنيكرز.', 'آيس كريم سنيكرز، كراميل، فول سوداني، شوكولاتة.', 'وافل', 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 65),
('ic-4', 'بوظة عنبر (Anbar Ice Cream)', 'ice-cream', 350, 'بوظة عربية بالقشطة والمستكة والفستق الحلبي على الأصول.', 'حليب طازج، مستكة أصلية، سحلب، قشطة، فستق حلبي مدقوق.', 'قهوة شرقية', 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=700&q=80', 'توقيع الدار', ARRAY['v'], true, true, 66),
('ic-5', 'بوظة مشكلة (Mixed Ice Cream)', 'ice-cream', 350, 'تشكيلة كرات آيس كريم متنوعة من الفواكه والشوكولاتة والفانيليا.', 'كرات بوظة: فريز، مانجو، شوكولاتة، فانيليا، مكسرات.', 'سلطة فواكه', 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 67),
('ic-6', 'بوظة حسب الطلب (Custom Order Ice Cream)', 'ice-cream', 350, 'اختر نكهاتك المفضلة والإضافات من تشكيلة بوظة عنبر.', 'نكهات حسب اختيار الزبون مع الصوصات والمكسرات.', 'أي مشروب ساخن', 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=700&q=80', 'حسب ذوقك', ARRAY['v'], true, false, 68),

-- -----------------------------------------------------------------------------
-- 🥞 10. كريب (Crepe)
-- -----------------------------------------------------------------------------
('cr-1', 'كريب فواكه (Fruits Crepe)', 'crepe', 350, 'عجينة كريب فرنسية رقيقة محشوة ومزينة بشرائح الفواكه الطازجة.', 'كريب طازج، موز، فراولة، كيوي، صوص شوكولاتة بيضاء.', 'عصير برتقال فريش', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 69),
('cr-2', 'كريب كيت كات (KitKat Crepe)', 'crepe', 350, 'كريب محشو بأصابع كيت كات المقرمشة وصوص الشوكولاتة.', 'كريب، أصابع كيت كات، شوكولاتة بالحليب، مكسرات.', 'كابتشينو', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 70),
('cr-3', 'كريب فستق (Pistachio Crepe)', 'crepe', 350, 'كريب غني بصلصة الفستق الحلبي الفاخرة والفستق المجروش.', 'كريب، زبدة فستق حلبي، فستق محمص، شوكولاتة بيضاء.', 'سبانيش لاتيه', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=700&q=80', 'مميز جداً', ARRAY['v'], true, true, 71),
('cr-4', 'كريب عنبر (Anbar Crepe)', 'crepe', 350, 'كريب توقيع عنبر المزيّن بثلاثة أنواع شوكولاتة ومكسرات وقشطة.', 'كريب، شوكولاتة نوتيلا، شوكولاتة بيضاء، كيندر، مكسرات، قشطة.', 'قهوة تركية', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=700&q=80', 'توقيع عنبر', ARRAY['v'], true, true, 72),
('cr-5', 'كريب كيندر (Kinder Crepe)', 'crepe', 350, 'كريب محشو بقطع شوكولاتة كيندر وصوص الكيندر بوينو.', 'كريب، شوكولاتة كيندر، صوص بوينو بالحليب.', 'آيس كافيه', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 73),
('cr-6', 'كريب نوتيلا (Nutella Crepe)', 'crepe', 350, 'كريب كلاسيكي مغطى بغزارة بشوكولاتة نوتيلا الإيطالية.', 'كريب رقيق، نوتيلا أصلية، مكسرات بندق.', 'إسبريسو', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=700&q=80', 'كلاسيك', ARRAY['v'], true, false, 74),
('cr-7', 'كريب سنيكرز (Snickers Crepe)', 'crepe', 350, 'كريب محشو بالفول السوداني والكراميل وصوص سنيكرز.', 'كريب، سنيكرز، كراميل، فول سوداني مقرمش.', 'مكياتو', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 75),

-- -----------------------------------------------------------------------------
-- 🍰 11. سبيشال سويت (Special Sweets)
-- -----------------------------------------------------------------------------
('ss-1', 'تيراميسو (Tiramisu)', 'special-sweets', 400, 'حلوى إيطالية كلاسيكية من بسكويت ليدي فينجر المشرب بالإسبريسو وكريمة الماسكاربوني.', 'بسكويت ليدي فينجر، إسبريسو، جبن ماسكاربوني، بودرة كاكاو.', 'إسبريسو سنغل', 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=700&q=80', 'إيطالي كلاسيك', ARRAY['v'], true, true, 76),
('ss-2', 'براونيز (Brownies)', 'special-sweets', 400, 'قطعة كيك شوكولاتة غنية وطرية تُقدم دافئة مع آيس كريم.', 'شوكولاتة داكنة، زبدة، مكسرات جوز، آيس كريم فانيليا.', 'كابتشينو', 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 77),
('ss-3', 'بنانا سويت (Banana Sweet)', 'special-sweets', 400, 'حلوى الموز بالكراميل والشوكولاتة والآيس كريم والمكسرات.', 'موز طازج، صوص كراميل دافئ، شوكولاتة، بوظة.', 'وايت لاتيه', 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 78),
('ss-4', 'فوندون الشوكولاتة (Chocolate Fondant)', 'special-sweets', 400, 'كيكة لافا ساخنة محشوة بقلب شوكولاتة سائلة تذوب بالفم.', 'كيك شوكولاتة، لافا سائلة، سكر بودرة، آيس كريم.', 'قهوة سادة', 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=700&q=80', 'الأكثر طلباً', ARRAY['v'], true, true, 79),
('ss-5', 'كأتو كلاس (Gateau Class)', 'special-sweets', 400, 'قطعة كاتو فرنسية فاخرة بطبقات الكريمة والشوكولاتة.', 'كيك إسفنجي، كريمة شانتيه، جناش شوكولاتة.', 'شاي إنجليزي', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 80),
('ss-6', 'وافل بلجيكي (Belgian Waffle)', 'special-sweets', 400, 'وافل بلجيكي مقرمش وهش مع الشوكولاتة والفواكه.', 'عجين وافل ذهبي، نوتيلا، شوكولاتة بيضاء، فراولة، موز.', 'ميلك شيك', 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 81),
('ss-7', 'رول كيك (Roll Cake)', 'special-sweets', 400, 'كيك سويس رول طري محشو بالكريمة المخملية وصوص التوت.', 'كيك رول إسفنجي، كريمة خفيفة، صوص توت وشوكولاتة.', 'لاتيه كراميل', 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 82),
('ss-8', 'بيرمادا كيك (Bermuda Cake)', 'special-sweets', 600, 'كيكة بيرمودا الهرمية الخاصة بحجم كبير وغنية بالطبقات والمكسرات.', 'طبقات كيك هرمي، موس شوكولاتة، كراميل، مكسرات فاخرة.', 'موكاشينو', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=700&q=80', 'سبيشال فاخر', ARRAY['v'], true, true, 83),

-- -----------------------------------------------------------------------------
-- 🥗 12. السلطات - حلويات (Dessert Salads)
-- -----------------------------------------------------------------------------
('ds-1', 'سلطة فستق (Pistachio Dessert Salad)', 'dessert-salads', 450, 'سلطة فواكه غنية بالقشطة وصوص الفستق الحلبي والمكسرات.', 'قطع فواكه، قشطة بلدية، صوص فستق، فستق حلبي مجروش.', 'موهيتو', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 84),
('ds-2', 'سلطة كيت كات (KitKat Dessert Salad)', 'dessert-salads', 450, 'سلطة فواكه مع أصابع كيت كات والشوكولاتة والمارشميلو.', 'فواكه مشكلة، كيت كات، صوص شوكولاتة، كريمة.', 'فرابيه ليمون', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 85),
('ds-3', 'سلطة سنيكرز (Snickers Dessert Salad)', 'dessert-salads', 450, 'سلطة فواكه ممزوجة بقطع سنيكرز والكراميل والفول السوداني.', 'فواكه، سنيكرز، كراميل، صوص شوكولاتة، مكسرات.', 'آيس كافيه', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 86),
('ds-4', 'سلطة تويكس (Twix Dessert Salad)', 'dessert-salads', 450, 'سلطة فواكه مع أصابع تويكس بالبسكويت والكراميل.', 'فواكه مشكلة، أصابع تويكس، صوص كراميل، شوكولاتة.', 'مكياتو', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 87),
('ds-5', 'سلطة عنبر سويت (Anbar Dessert Salad)', 'dessert-salads', 450, 'سلطة فواكه عنبر الملكية بالقشطة والعسل والمكسرات والشوكولاتة.', 'فواكه طازجة، قشطة عربية، عسل جبلي، مكسرات فاخرة، شوكولاتة.', 'كوكتيل عنبر', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80', 'توقيع عنبر', ARRAY['v'], true, true, 88),
('ds-6', 'سلطة فواكه (Fresh Fruits Salad)', 'dessert-salads', 450, 'سلطة فواكه طبيعية طازجة مشكلة مع عصير فريش.', 'تفاح، موز، فراولة، كيوي، أناناس، عصير مانجو.', 'عصير برتقال', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80', 'صحي وطازج', ARRAY['vg', 'gf'], true, false, 89),
('ds-7', 'سلطة كيندر (Kinder Dessert Salad)', 'dessert-salads', 450, 'سلطة فواكه ممزوجة بشوكولاتة كيندر وصوص البوينو.', 'فواكه، شوكولاتة كيندر، بوينو، صوص شوكولاتة بيضاء.', 'كابتشينو', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 90),

-- -----------------------------------------------------------------------------
-- 🥗 13. السلطات (Salads)
-- -----------------------------------------------------------------------------
('sal-1', 'جينرال سلاد (General Salad)', 'salads', 800, 'سلطة جنرال الشهية الغنية بقطع الدجاج والخضار المقرمشة والجبن والصوص الخاص.', 'خس روماني، دجاج متبل، طماطم كرزية، ذرة، جبن شيدر، دريسينغ جنرال.', 'موهيتو بارد', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=700&q=80', 'طبق مميز', ARRAY['gf'], true, true, 91),
('sal-2', 'سيزر دجاج (Chicken Caesar Salad)', 'salads', 750, 'سلطة سيزر الكلاسيكية بشرائح صدور الدجاج المشوية وجبن البارميزان والخبز المحمص.', 'خس مقرمش، صدر دجاج مشوي، خبز كروتون، جبن بارميزان، صوص سيزر أصلي.', 'آيس تي خوخ', 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=700&q=80', 'الأكثر مبيعاً', NULL, true, true, 92),
('sal-3', 'بوب كورن سلاد (Popcorn Salad)', 'salads', 750, 'سلطة مقرمشة وممتعة بقطع دجاج البوب كورن وصوص الرانش والجبن.', 'خضار مشكلة، قطع بوب كورن دجاج مقرمشة، ذرة حلوة، صوص رانش.', 'بيبسي تنك', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 93),
('sal-4', 'سيزر لحومات (Meats Caesar Salad)', 'salads', 800, 'سلطة سيزر الغنية بشرائح اللحوم الباردة والمشوية مع جبن البارميزان.', 'خس، شرائح لحم بيف مدخن، بيبروني، جبن بارميزان، صوص سيزر.', 'مياه فوارة', 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 94),
('sal-5', 'فتوش (Fattoush Salad)', 'salads', 600, 'فتوش شامي تقليدي غني بدبس الرمان والخبز المقلي والنعناع وزيت الزيتون البكر.', 'خيار، طماطم، خس، فجل، بقلة، نعناع، خبز مقرمش، دبس رمان، سماق.', 'عيران بلدي', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80', 'شامي أصيل', ARRAY['vg'], true, false, 95),
('sal-6', 'يونانية (Greek Salad)', 'salads', 600, 'سلطة يونانية منعشة بمكعبات جبنة الفيتا والزيتون الأسود والأوريغانو وزيت الزيتون.', 'خيار، طماطم، فلفل رومي، بصل أحمر، جبن فيتا، زيتون كالاماتا، زيت زيتون.', 'عصير ليمون ونعناع', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v', 'gf'], true, false, 96),
('sal-7', 'سلطة مواسم (Seasons Salad)', 'salads', 500, 'تشكيلة من خضار الموسم الطازجة المتبلة بالليمون وزيت الزيتون البكر.', 'خضار موسمية مشكلة، طماطم، خيار، خس، جزر، زيت وليمون.', 'مياه معدنية', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=700&q=80', 'صحي وخفيف', ARRAY['vg', 'gf'], true, false, 97),
('sal-8', 'سلطة معكرونة (Pasta Salad)', 'salads', 750, 'سلطة باستا إيطالية باردة مع الخضار والمايونيز والذرة والزيتون.', 'مكرونة فوسيلي، خضار مشكلة، ذرة، زيتون أسود، مايونيز وأعشاب.', 'آيس تي', 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 98),

-- -----------------------------------------------------------------------------
-- 🥪 14. صندويش (Sandwiches)
-- -----------------------------------------------------------------------------
('sw-1', 'صندويش سبايسي (Spicy Sandwich)', 'sandwiches', 650, 'صندويش دجاج سبايسي حار مع صوص الشطة الخاصة والجبن والخس.', 'دجاج حار متبل، مايونيز حار، جبن شيدر، خس، خبز صامولي طازج.', 'بيبسي مثلج', 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=700&q=80', 'حار', NULL, true, false, 99),
('sw-2', 'صندويش ناغيت (Nugget Sandwich)', 'sandwiches', 650, 'قطع ناغيت دجاج مقرمشة مع صوص المايونيز والكاتشب والبطاطا.', 'ناغيت دجاج مقلي، بطاطا مقلية، مايونيز، مخلل، خبز صامولي.', 'عصير برتقال', 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 100),
('sw-3', 'صندويش زنجر (Zinger Sandwich)', 'sandwiches', 700, 'فيليه زنجر مقرمش وحار مع الجبن وصوص الزنجر الخاص.', 'دجاج زنجر كريسبي حار، جبن، خس مقرمش، صوص رانش حار.', 'موهيتو', 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=700&q=80', 'الأكثر طلباً', NULL, true, true, 101),
('sw-4', 'صندويش كريسبي (Crispy Sandwich)', 'sandwiches', 650, 'شرائح دجاج كريسبي مقرمشة مع الخس والمايونيز والجبن الذائب.', 'ستربس دجاج كريسبي، مايونيز ثوم، خس، مخلل خيار.', 'بيبسي', 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 102),
('sw-5', 'صندويش غواصة (Submarine Sandwich)', 'sandwiches', 700, 'صندويش صب مارين كلاسيكي محشو بالدجاج واللحوم والجبن والذرة والفطر.', 'دجاج متبل، سلامي، فطر، ذرة، جبن موزاريلا، مايونيز.', 'مشروب غازي', 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=700&q=80', 'كبير ومميز', NULL, true, false, 103),
('sw-6', 'صندويش فاهيتا (Fajita Sandwich)', 'sandwiches', 700, 'دجاج فاهيتا مكسيكي متبل مع الفلفل الملون والبصل والفطر والموزاريلا.', 'صدور دجاج فاهيتا، فلفل ملون، بصل مشوي، فطر، جبن موزاريلا، بهارات مكسيكية.', 'موهيتو ليمون', 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 104),
('sw-7', 'صندويش مكسيكانو (Mexicano Sandwich)', 'sandwiches', 700, 'دجاج مكسيكانو حار ومتبل بالخلطة المكسيكية مع الذرة والفطر.', 'دجاج مكسيكانو، صوص حار، ذرة حلوة، فطر، جبن شيدر.', 'بيبسي', 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=700&q=80', 'حار ولذيذ', NULL, true, false, 105),
('sw-8', 'صندويش هوت دوغ (Hot Dog Sandwich)', 'sandwiches', 650, 'نقانق هوت دوغ مدخنة مع الخردل والكاتشب والمخلل والجبن.', 'هوت دوغ فاخر، خردل ديجون، كاتشب، مخلل، جبن شيدر ذائب.', 'مشروب غازي', 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 106),

-- -----------------------------------------------------------------------------
-- 🥩 15. عجل (Veal & Beef)
-- -----------------------------------------------------------------------------
('bf-1', 'بيف ماشروم (Beef Mushroom)', 'beef', 1250, 'شرائح لحم عجل طري مطهو بصلصة الفطر الكريمية الغنية مع الأرز أو البطاطا.', 'لحم عجل طازج، فطر طازج، صوص كريمة غنية، بهارات عطرية، بطاطا أو رز.', 'عصير رمان فريش', 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=700&q=80', 'طبق فاخر', ARRAY['gf'], true, true, 107),
('bf-2', 'استروغونوف بيف (Beef Stroganoff)', 'beef', 1250, 'بيف ستروغانوف كلاسيكي من لحم العجل مع الفطر والبصل وصوص الكريمة والخردل.', 'شرائح لحم عجل، بصل، فطر، ساور كريم، خردل، باستا أو رز.', 'آيس تي فريش', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=700&q=80', 'كلاسيك عالمي', NULL, true, true, 108),
('bf-3', 'شرحات حمص وثوم (Beef Slices with Hummus & Garlic)', 'beef', 1250, 'شرحات لحم عجل بلدي طرية مع صوص الحمص والثوم والليمون وزيت الزيتون.', 'لحم عجل شرحات، صوص ثوم وحامض، حمص، زيت زيتون بكر.', 'عيران بلدي', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=700&q=80', 'شامي أصيل', ARRAY['gf'], true, false, 109),
('bf-4', 'فيلادلفيا بيف (Philadelphia Beef)', 'beef', 1250, 'شرائح لحم ستيك العجل مع البصل والفلفل والفطر وجبن البروفولون المذاب.', 'ستيك عجل شرائح، فلفل رومي، بصل مشوي، فطر، جبن مذاب.', 'بيبسي بارد', 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=700&q=80', 'أمريكي شهير', NULL, true, false, 110),

-- -----------------------------------------------------------------------------
-- 🍟 16. المقبلات (Appetizers)
-- -----------------------------------------------------------------------------
('app-1', 'موزاريلا سموكي (Smoky Mozzarella)', 'appetizers', 600, 'كرات جبن موزاريلا مدخنة مقرمشة مع صوص التغميس الخاص.', 'جبن موزاريلا مدخن، بقسماط مقرمش، صوص مارينارا.', 'موهيتو', 'https://images.unsplash.com/photo-1531749668029-2db88e4276c7?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 111),
('app-2', 'رول تشيكن (Chicken Roll)', 'appetizers', 600, 'رولات دجاج مقرمشة محشوة بالجبن والأعشاب.', 'دجاج مفروم، جبن، أعشاب عطرية، صوص غمس.', 'آيس كافيه', 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 112),
('app-3', 'فريت بطاطا (French Fries)', 'appetizers', 300, 'أصابع بطاطا ذهبية مقرمشة ومتبلة بالبهارات الخاصة.', 'بطاطا مقلية طازجة، بهارات عنبر، كاتشب ومايونيز.', 'أي مشروب غازي', 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=700&q=80', 'مقرمش', ARRAY['vg', 'gf'], true, false, 113),
('app-4', 'بطاطا شيدر (Cheddar Fries)', 'appetizers', 600, 'بطاطا مقلية مغطاة بصوص جبن الشيدر الذائب وحبيبات الهالبينو.', 'بطاطا مقلية، صوص جبن شيدر ساخن، هالبينو (اختياري).', 'بيبسي', 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=700&q=80', 'الأكثر طلباً', ARRAY['v'], true, true, 114),
('app-5', 'بطاطا بوتين (Poutine Fries)', 'appetizers', 600, 'بطاطا بوتين الكندية بقطع الجبن وصوص الجريفي الغني.', 'بطاطا مقلية، صوص جريفي ساخن، قطع جبن ذائبة.', 'مشروب غازي', 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 115),
('app-6', 'بوب كورن دجاج (Popcorn Chicken)', 'appetizers', 800, 'قطع دجاج مقرمشة بحجم اللقمة بتتبيلة لذيذة.', 'صدور دجاج مقرمشة، صوص تراجع حار، صوص باربيكيو.', 'عصير ليموناضة', 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 116),
('app-7', 'برك جبنة (Cheese Börek / Rolls)', 'appetizers', 350, 'أصابع برك مقرمشة محشوة بالجبن البلدي والأعشاب.', 'عجينة رقائق مقرمشة، جبن عكاوي وموزاريلا، حبة البركة.', 'شاي أحمر', 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=700&q=80', 'تقليدي', ARRAY['v'], true, false, 117),
('app-8', 'صحن رز (Rice Plate)', 'appetizers', 250, 'صحن أرز بسمتي فاخر مطهو بالبهارات الخفيفة.', 'أرز بسمتي فاخر، زبدة، بهارات خفيفة.', 'أطباق اللحوم والدجاج', 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 118),
('app-9', 'تشيكن ستيكس (Chicken Sticks)', 'appetizers', 800, 'أصابع دجاج مقرمشة بتتبيلة خاصة مع صوص الخردل والعسل.', 'دجاج كريسبي مقرمش، صوص هوني موستارد.', 'عصير مانجو', 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 119),
('app-10', 'أصابع موزاريلا (Mozzarella Sticks)', 'appetizers', 450, 'أصابع جبن موزاريلا مقلية مقرمشة تمط مع صوص الكوكتيل.', 'جبن موزاريلا، بقسماط أعشاب، صوص كوكتيل.', 'موهيتو', 'https://images.unsplash.com/photo-1531749668029-2db88e4276c7?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 120),
('app-11', 'بطاطا ويدجز (Potato Wedges)', 'appetizers', 400, 'أجنحة بطاطا مخبوزة ومتبلة بالأعشاب والبابريكا وزيت الزيتون.', 'بطاطا ويدجز بقشرتها، بهارات أعشاب، صوص ثوم.', 'بيبسي', 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg', 'gf'], true, false, 121),
('app-12', 'حلقات بصل (Onion Rings)', 'appetizers', 300, 'حلقات بصل مقرمشة وذهبية مع صوص الباربيكيو.', 'بصل طازج، خليط مقرمش، صوص باربيكيو.', 'مشروب غازي', 'https://images.unsplash.com/photo-1639024471287-032f66e5f39f?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['vg'], true, false, 122),

-- -----------------------------------------------------------------------------
-- 🍝 17. باستا (Pasta)
-- -----------------------------------------------------------------------------
('pas-1', 'كربونارا (Carbonara Pasta)', 'pasta', 950, 'باستا إيطالية أصيلة بصلصة الكريمة الغنية والبيف بيكن والبارميزان.', 'باستا فيتوتشيني، بيف بيكن مقدد، بيض، كريمة طبخ، جبن بارميزان.', 'عصير ليمون فريش', 'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=700&q=80', 'إيطالي أصلي', NULL, true, true, 123),
('pas-2', 'الفريدو (Fettuccine Alfredo)', 'pasta', 900, 'فيتوتشيني ألفريدو بصلصة الكريمة البيضاء وقطع الدجاج والفطر والبارميزان.', 'فيتوتشيني، صدور دجاج، فطر طازج، زبدة، كريمة طبخ، بارميزان.', 'آيس تي خوخ', 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=700&q=80', 'الأكثر طلباً', NULL, true, true, 124),
('pas-3', 'الفونجي (Fungi Pasta)', 'pasta', 750, 'باستا شهية بصلصة الفطر البري والأعشاب الإيطالية العطرية.', 'باستا، فطر طازج، ثوم، زيت زيتون، ريحان، صوص أبيض خفيف.', 'مياه فوارة', 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 125),
('pas-4', 'أرابيانا سبايسي (Arrabbiata Spicy Pasta)', 'pasta', 800, 'باستا بيني بصلصة الطماطم الحارة والثوم والفلفل الحار والريحان.', 'بيني باستا، صلصة طماطم إيطالية، فلفل حار، ثوم، ريحان، زيت زيتون.', 'عصير برتقال', 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=700&q=80', 'حار نباتي', ARRAY['vg'], true, false, 126),
('pas-5', 'بينا ناغيت (Penne Nugget Pasta)', 'pasta', 800, 'باستا بيني كريمية مع قطع الناغيت المقرمشة والجبن الذائب.', 'بيني باستا، قطع ناغيت كريسبي، صوص جبن كريمي، موزاريلا.', 'بيبسي', 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 127),
('pas-6', 'تشيكن تشيدر باستا (Chicken Cheddar Pasta)', 'pasta', 900, 'باستا مع قطع الدجاج وصوص جبن الشيدر الذهبي الذائب.', 'باستا، دجاج مشوي، صوص جبن شيدر أصلي، بهارات أعشاب.', 'موهيتو', 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=700&q=80', 'غني بالجبن', NULL, true, false, 128),

-- -----------------------------------------------------------------------------
-- 🧀 18. بلوميات (Plomi / Halloumi Dishes)
-- -----------------------------------------------------------------------------
('pl-1', 'بلومي شيش (Bloumi Shish)', 'plomi', 1000, 'قطع شيش طاووق متبلة مشوية مع جبن البلومي المقرمش والصوص.', 'دجاج شيش طاووق، جبن بلومي مشوي، صوص بلومي الخاص، خضار مشوية.', 'عيران بلدي', 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=700&q=80', 'مميز', NULL, true, true, 129),
('pl-2', 'بلومي كباب (Bloumi Kebab)', 'plomi', 1000, 'كباب لحم مشوي على الفحم مغطى بجبن البلومي الذائب والتوابل.', 'كباب لحم غنم وعجل، جبن بلومي ذائب، صوص أحمر، خبز ساخن.', 'عصير رمان', 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=700&q=80', 'فاخر', NULL, true, false, 130),
('pl-3', 'بلومي هوت دوغ (Bloumi Hot Dog)', 'plomi', 900, 'نقانق هوت دوغ مشوية مع جبن البلومي والصلصة الخاصة.', 'هوت دوغ، جبن بلومي مشوي، خردل، مايونيز، بطاطا.', 'بيبسي', 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 131),
('pl-4', 'بلومي سجق (Bloumi Sujuk)', 'plomi', 1000, 'سجق بلدي متبل وحار مع قطع جبن البلومي المشوية والمكسرات.', 'سجق بلدي متبل، جبن بلومي، دبس رمان، صنوبر.', 'عصير ليمون ونعناع', 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=700&q=80', 'حار وشهي', NULL, true, false, 132),
('pl-5', 'بلومي عجل (Bloumi Veal)', 'plomi', 1250, 'شرائح لحم عجل طرية مع جبن البلومي المشوي والصلصة الغنية.', 'لحم عجل فاخر، جبن بلومي، فطر، صوص بني غني، بطاطا.', 'فرابيه ليمون', 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=700&q=80', 'سبيشال', NULL, true, true, 133),

-- -----------------------------------------------------------------------------
-- 🍔 19. برغر (Burgers)
-- -----------------------------------------------------------------------------
('bg-1', 'كلاسيك برغر (Classic Burger)', 'burgers', 650, 'برغر لحم بقري صافي مع الجبن والخس والطماطم وصوص البرغر الكلاسيكي.', 'برغر لحم بقري مشوي، جبن شيدر، خس، طماطم، مخلل، صوص كلاسيك.', 'بيبسي وفريت', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=80', 'كلاسيك', NULL, true, false, 134),
('bg-2', 'باربيكيو برغر (BBQ Burger)', 'burgers', 650, 'برغر لحم مشوي مع صوص الباربيكيو المدخن وحلقات البصل والجبن.', 'برغر لحم، صوص باربيكيو مدخن، حلقات بصل مقرمشة، جبن شيدر.', 'مشروب غازي', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 135),
('bg-3', 'تشيكن برغر (Chicken Burger)', 'burgers', 550, 'برغر فيليه دجاج مقرمش مع المايونيز والخس الطازج والجبن.', 'فيليه دجاج كريسبي، مايونيز، خس مقرمش، خبز بريوش.', 'عصير فريش', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 136),
('bg-4', 'ميكس برغر (Mix Burger)', 'burgers', 800, 'برغر دبل يجمع بين شريحة لحم بقري وفيليه دجاج مقرمش مع دبل جبن.', 'شريحة لحم بقري، فيليه دجاج كريسبي، جبن شيدر مزدوج، صوص سري.', 'موهيتو فريش', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=80', 'حجم كبير', NULL, true, true, 137),
('bg-5', 'بيغ ماك برغر (Big Mac Burger)', 'burgers', 650, 'طبقات برغر اللحم مع صلصة البيغ ماك الشهيرة والجبن والمخلل.', 'طبقتين لحم بقري، خبز بالسمسم، خس، بصل، مخلل، صوص بيغ ماك.', 'بيبسي', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=80', 'شهير', NULL, true, false, 138),
('bg-6', 'عنبر برغر (Anbar Burger)', 'burgers', 800, 'برغر عنبر الملكي الخاص مع صوص المشروم والجبن والبيكون المقرمش.', 'لحم بقري أنغوس فاخر، صوص فطر طازج، بيف بيكون، جبن إيمينتال، بصل مكرمل.', 'عصير عنبر كوكتيل', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=80', 'توقيع عنبر', NULL, true, true, 139),
('bg-7', 'شيش برغر (Shish Burger)', 'burgers', 550, 'برغر شيش طاووق دجاج مشوي مع صوص الثومية والمخلل والخس.', 'شيش طاووق مشوي، ثومية، مخلل، خس، خبز برغر طازج.', 'عيران', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 140),

-- -----------------------------------------------------------------------------
-- 🍕 20. بيتزا (Pizza)
-- -----------------------------------------------------------------------------
('pz-1', 'بيتزا بيبروني (Pepperoni Pizza)', 'pizza', 850, 'بيتزا إيطالية بصلصة الطماطم وجبن الموزاريلا وشرائح البيبروني البقري المقرمشة.', 'عجينة بيتزا هشة، صلصة طماطم إيطالية، موزاريلا، شرائح بيبروني بقري.', 'بيبسي', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80', 'كلاسيك', NULL, true, false, 141),
('pz-2', 'بيتزا سجق (Sujuk Pizza)', 'pizza', 950, 'بيتزا بالسجق البلدي المتبل والجبن والفلفل الأخضر والزيتون.', 'عجينة بيتزا، سجق بلدي حار، موزاريلا، فلفل، زيتون.', 'عيران أو بيبسي', 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=700&q=80', 'شرقي', NULL, true, false, 142),
('pz-3', 'بيتزا فطر (Mushroom Pizza)', 'pizza', 850, 'بيتزا بصلصة الطماطم والموزاريلا وشرائح الفطر الطازج والأوريغانو.', 'عجينة بيتزا، صلصة، موزاريلا، فطر طازج، أوريغانو، زيت زيتون.', 'مياه فوارة', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80', NULL, ARRAY['v'], true, false, 143),
('pz-4', 'بيتزا مارغاريتا (Margherita Pizza)', 'pizza', 750, 'بيتزا مارغاريتا نابولية بصلصة الطماطم وجبن الموزاريلا والريحان الطازج.', 'عجينة مخمرة، صلصة طماطم سان مارزانو، موزاريلا، ريحان طازج.', 'موهيتو', 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=700&q=80', 'أصلي', ARRAY['v'], true, false, 144),
('pz-5', 'بيتزا كابري (Capri Pizza)', 'pizza', 950, 'بيتزا كابري الإيطالية بالدجاج والمشروم والأعشاب وزيت الزيتون.', 'عجينة بيتزا، دجاج، فطر، صلصة كابري، جبن موزاريلا.', 'آيس تي', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 145),
('pz-6', 'بيتزا فصول أربعة (Four Seasons Pizza)', 'pizza', 850, 'بيتزا كواترو ستاجيوني مقسمة إلى 4 أقسام (فطر، بيبروني، خضار، جبن).', 'عجينة، موزاريلا، بيبروني، فطر، زيتون، فلفل رومي، خرشوف.', 'مشروب غازي', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80', 'تنوع رائع', NULL, true, false, 146),
('pz-7', 'تشيكن باشاميل بيتزا (Chicken Béchamel Pizza)', 'pizza', 900, 'بيتزا مبتكرة بصلصة البشاميل الكريمية وقطع الدجاج والفطر والجبن.', 'عجينة بيتزا، صوص بشاميل غني، صدور دجاج، فطر، موزاريلا.', 'عصير ليمون ونعناع', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80', 'كريمي', NULL, true, false, 147),
('pz-8', 'بيتزا سبايسي (Spicy Pizza)', 'pizza', 950, 'بيتزا حارة بصلصة الشطة والفلفل الحار واللحم المفروم والموزاريلا.', 'صلصة طماطم حارة، هالبينو، لحم مفروم، فلفل حار، موزاريلا.', 'مشروب بارد', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80', 'حار جداً', NULL, true, false, 148),
('pz-9', 'بيتزا خضار (Vegetables Pizza)', 'pizza', 800, 'بيتزا خضار طازجة مع الفلفل الملون والفطر والزيتون والذرة والبصل.', 'صلصة طماطم، موزاريلا، فلفل ملون، فطر، زيتون أسود، ذرة، طماطم.', 'عصير فريش', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80', 'نباتي صحي', ARRAY['v'], true, false, 149),
('pz-10', 'بيتزا عنبر الخاصة (Anbar Special Pizza)', 'pizza', 1050, 'بيتزا عنبر الفاخرة المشكلة بأجود اللحوم والدجاج والأجبان الأربعة.', 'صلصة عنبر السرية، دجاج، ستيك لحم، سجق، أربعة أجبان، فطر طازج.', 'غروب عنبر', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80', 'توقيع عنبر', NULL, true, true, 150),
('pz-11', 'بيتزا لحومات (Meats Pizza)', 'pizza', 1000, 'بيتزا مخصصة لعشاق اللحوم تجمع البيبروني والسجق واللحم البقري والبيكون.', 'صلصة، موزاريلا، بيبروني، سجق، لحم بقري مفروم، بيف بيكون.', 'بيبسي عائلي', 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=700&q=80', 'غنية باللحوم', NULL, true, false, 151),
('pz-12', 'بيتزا هوت دوغ (Hot Dog Pizza)', 'pizza', 900, 'بيتزا محبوبة بشرائح الهوت دوغ وجبن الموزاريلا والذرة.', 'صلصة طماطم، هوت دوغ شرائح، موزاريلا، ذرة، خردل خفيف.', 'مشروب غازي', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 152),
('pz-13', 'بيتزا مكسيكانو (Mexicano Pizza)', 'pizza', 950, 'بيتزا دجاج مكسيكانو مع الفلفل الحار والذرة والصلصة المكسيكية.', 'عجينة بيتزا، دجاج مكسيكانو، صوص سالسا، هالبينو، ذرة، موزاريلا.', 'موهيتو', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80', 'مكسيكي حار', NULL, true, false, 153),
('pz-14', 'بيتزا مدخن (Smoked Pizza)', 'pizza', 850, 'بيتزا باللحوم والدجاج المدخن وجبن الشيدر والموزاريلا وصوص الباربيكيو.', 'عجينة بيتزا، دجاج مدخن، تركي مدخن، صوص باربيكيو، موزاريلا.', 'آيس تي', 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80', 'نكهة تدخين', NULL, true, false, 154),

-- -----------------------------------------------------------------------------
-- 👨‍👩‍👧‍👦 21. وجبات عائلي (Family Meals)
-- -----------------------------------------------------------------------------
('fam-1', 'طبق عنبر الغني العائلي (Rich Anbar Family Plate)', 'family-meals', 2250, 'وليمة عنبر العائلية الفاخرة المشكلة من الدجاج واللحوم والمقبلات والبطاطا والصلصات.', 'تشكيلة ستيك دجاج ولحم، كريسبي، أصابع جبن، أرز، بطاطا ويدجز، سلطة، صلصات متنوعة.', 'بيبسي عائلي', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=700&q=80', 'وليمة الدار', NULL, true, true, 155),
('fam-2', 'وجبة كاسبر العائلية (Casper Family Meal)', 'family-meals', 2500, 'وجبة عائلية ضخمة ومقرمشة تكفي 4-6 أشخاص مع تشكيلة الوجبات والمقبلات.', 'دجاج كاسبر المميز، كوردون بلو، ناغيتس، بطاطا شيدر، سلطة سيزر، صلصات.', 'بيبسي عائلي', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=700&q=80', 'العرض الأكبر', NULL, true, true, 156),

-- -----------------------------------------------------------------------------
-- 🍗 22. الوجبات الرئيسية (Main Meals)
-- -----------------------------------------------------------------------------
('mm-1', 'أماندا تشيكن (Amanda Chicken Meal)', 'main-meals', 1050, 'صدر دجاج محشو بالأجبان والمشروم بصلصة أماندا الكريمية مع الأرز والبطاطا.', 'صدر دجاج محشو، صوص أماندا الكريمي، فطر، جبن، رز أو بطاطا، سوتيه.', 'موهيتو ليمون', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', 'سبيشال', NULL, true, true, 157),
('mm-2', 'تشيكن ألاكياف (Chicken Al-Kief)', 'main-meals', 1050, 'صدر دجاج ملفوف ومحشو بالزبدة والأعشاب ومقلي ومقرمش بأسلوب كيف الكلاسيكي.', 'صدر دجاج رول، زبدة أعشاب وثوم، بقسماط ذهبي، بطاطا بوريه، خضار.', 'عصير برتقال فريش', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', 'كلاسيك عالمي', NULL, true, false, 158),
('mm-3', 'تشيكن سيراتشا (Sriracha Chicken)', 'main-meals', 1000, 'دجاج مشوي بصلصة السيراتشا الحارة والتوابل الآسيوية مع الأرز المبخر.', 'دجاج متبل، صلصة سيراتشا حارة، سمسم، بصل أخضر، أرز بسمتي.', 'بيبسي مثلج', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', 'حار لاذع', NULL, true, false, 159),
('mm-4', 'ميكس بيف بلاتر (Mix Beef Plate)', 'main-meals', 1050, 'تشكيلة لحوم بيف مشوية بصلصات متنوعة مع الخضار والبطاطا.', 'شرائح لحم عجل بيف، صوص فطر، صوص فلفل أسود، بطاطا مقلية، خضار سوتيه.', 'عصير رمان', 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=700&q=80', 'لعشاق اللحم', ARRAY['gf'], true, true, 160),
('mm-5', 'تشيكن تشيبس (Chicken Chips Meal)', 'main-meals', 900, 'شرائح دجاج كرسبي رقيقة ومقرمشة كالشيبس مع صوص التغميس والبطاطا.', 'دجاج كريسبي شيبس، بطاطا مقلية، صوص رانش، صوص هوني موستارد.', 'مشروب غازي', 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=700&q=80', 'مقرمش وخفيف', NULL, true, false, 161),
('mm-6', 'استروغونوف تشيكن (Chicken Stroganoff)', 'main-meals', 1050, 'شرائح صدور دجاج طرية بصلصة الستروغانوف الغنية بالفطر والساور كريم مع الأرز.', 'صدور دجاج، فطر طازج، كريمة طبخ، خردل، بصل، أرز بسمتي فاخر.', 'آيس تي خوخ', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 162),
('mm-7', 'لاميرا تشيكن (Lameera Chicken)', 'main-meals', 1000, 'دجاج لاميرا بصلصة الليمون والكريمة والأعشاب العطرية الخفيفة.', 'دجاج مشوي، صوص ليمون وكريمة، كبر، أعشاب، خضار وبطاطا.', 'عصير كيوي', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 163),
('mm-8', 'كوردون بلو (Cordon Bleu Meal)', 'main-meals', 1000, 'صدور دجاج محشوة بالتركي المدخن وجبن الموزاريلا المقلي المقرمش.', 'صدر دجاج محشو، تركي مدخن، موزاريلا، صوص جبن، بطاطا مقلية.', 'بيبسي', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', 'الأكثر مبيعاً', NULL, true, true, 164),
('mm-9', 'فلامينكو تشيكن (Flamenco Chicken)', 'main-meals', 1150, 'وجبة دجاج فلامينكو الإسبانية المتبلة مع صلصة الفلفل الحلو والجبن الذائب.', 'دجاج متبل، صلصة فلامينكو إسبانية، فلفل، جبن ذائب، رز أو بطاطا.', 'فرابيه ليمون', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', 'مميز', NULL, true, false, 165),
('mm-10', 'كروز تشيكن (Cruz Chicken)', 'main-meals', 1150, 'دجاج كروز المميز بتتبيلة الباربكيو المدخن والأجبان المشكلة.', 'دجاج كروز، صوص تدخين، جبن شيدر وموزاريلا، بطاطا ويدجز.', 'موهيتو', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 166),
('mm-11', 'عنبر تشيكن بلاتر (Anbar Chicken Platter)', 'main-meals', 1100, 'طبق دجاج عنبر الملكي المحضر بصلصة الدار الخاصة والمكسرات والأرز.', 'صدور دجاج متبلة بخلطة عنبر، صوص كريمي فاخر، فستق، صنوبر، أرز مبخر.', 'كوكتيل عنبر', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', 'توقيع عنبر', NULL, true, true, 167),
('mm-12', 'بامبينو تشيكن (Bambino Chicken)', 'main-meals', 1100, 'دجاج بامبينو الشهي بصلصة الطماطم الإيطالية والموزاريلا والريحان.', 'دجاج فيليه، صلصة طماطم ريحان، جبن موزاريلا، باستا أو بطاطا.', 'عصير تفاح', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 168),
('mm-13', 'تشيكن تشيدر وجبة (Chicken Cheddar Meal)', 'main-meals', 1050, 'صدور دجاج مشوية مغطاة بصوص جبن الشيدر الساخن والبطاطا المقلية.', 'دجاج مشوي، صوص شيدر وفير، بطاطا فريت، خضار سوتيه.', 'بيبسي', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', 'غني بالجبن', NULL, true, false, 169),
('mm-14', 'كاسبرسكي تشيكن (Kaspersky Chicken)', 'main-meals', 950, 'وجبة دجاج كاسبرسكي المقرمشة بتتبيلة خاصة وصوص التغميس.', 'دجاج كريسبي مقرمش، صوص كاسبرسكي الخاص، بطاطا مقلية، سلطة كولسلو.', 'مشروب غازي', 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 170),
('mm-15', 'شرحات دجاج حمص وثوم / بروفنسيال (Chicken Slices Hummus & Garlic / Provencal)', 'main-meals', 900, 'شرحات صدور دجاج طرية مطهوة بالثوم والحامض والكزبرة (بروفنسيال) مع الحمص.', 'صدور دجاج شرحات، ثوم، حامض، كزبرة، حمص، بطاطا.', 'عيران بلدي', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', 'شامي أصيل', ARRAY['gf'], true, false, 171),
('mm-16', 'وجبة مكسيكانو (Mexicano Meal)', 'main-meals', 950, 'طبق دجاج مكسيكانو الحار مع الفلفل الملون والفطر والذرة والأرز.', 'دجاج مكسيكانو حار، فلفل، ذرة، فطر، صوص حار، أرز بسمتي.', 'بيبسي بارد', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', 'حار ولذيذ', NULL, true, false, 172),
('mm-17', 'اسكالوب دجاج (Chicken Escalope)', 'main-meals', 950, 'شريحة إسكالوب دجاج كبيرة ومقرمشة تقدم مع البطاطا المقلية وصلصة التارتار.', 'فيليه دجاج مخفوق ومقرمش، بطاطا مقلية، صوص تارتار، خضار.', 'عصير ليموناضة', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', 'مفضل', NULL, true, false, 173),
('mm-18', 'وجبة فاهيتا دجاج (Chicken Fajita Meal)', 'main-meals', 950, 'طبق فاهيتا دجاج مكسيكي ساخن مع البصل والفلفل والموزاريلا وخبز التورتيلا.', 'دجاج فاهيتا، فلفل ملون، بصل مشوي، فطر، جبن، خبز تورتيلا، ساور كريم.', 'موهيتو', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 174),
('mm-19', 'وجبة غواصة (Submarine Meal Plate)', 'main-meals', 950, 'طبق الغواصة المشكل من الدجاج واللحوم والفطر والذرة والموزاريلا مع البطاطا.', 'دجاج متبل، سلامي، فطر، ذرة، موزاريلا، بطاطا مقلية، صوص.', 'مشروب غازي', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 175),
('mm-20', 'وجبة زنجر (Zinger Meal)', 'main-meals', 950, 'وجبة دجاج زنجر المقرمش والحار مع البطاطا وسلطة الكولسلو والصوص.', 'قطع زنجر حارة ومقرمشة، بطاطا فريت، صوص زنجر، كولسلو.', 'بيبسي', 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=700&q=80', 'حار مقرمش', NULL, true, true, 176),
('mm-21', 'وجبة ناغيت (Nugget Meal)', 'main-meals', 900, 'وجبة قطع ناغيت دجاج مقرمشة مع البطاطا المقلية والصوصات.', 'قطع ناغيت دجاج مقلية، بطاطا مقلية، كاتشب، مايونيز، عصير.', 'عصير برتقال', 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=700&q=80', 'محبوب الأطفال', NULL, true, false, 177),
('mm-22', 'وجبة سبايسي تشيكن (Spicy Chicken Meal)', 'main-meals', 900, 'دجاج سبايسي مقلي ومتبل بالشطة مع البطاطا وصلصة الثوم الحارة.', 'دجاج حار متبل، بطاطا مقلية، ثومية حارة، مخلل.', 'بيبسي', 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=700&q=80', 'حار', NULL, true, false, 178),
('mm-23', 'وجبة كريسبي (Crispy Meal)', 'main-meals', 900, 'أصابع ستربس دجاج كريسبي مقرمشة مع البطاطا المقلية وصلصة الثومية والكولسلو.', 'ستربس دجاج كريسبي، بطاطا مقلية، ثومية، كولسلو، خبز.', 'مشروب غازي', 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=700&q=80', 'الأكثر مبيعاً', NULL, true, true, 179),
('mm-24', 'كاساديا دجاج (Chicken Quesadilla)', 'main-meals', 950, 'كاساديا مكسيكية بخبز التورتيلا المحمص والمحشو بالدجاج المتبل والجبن الذائب والذرة.', 'تورتيلا محمص، دجاج فاهيتا، جبن موزاريلا وشيدر، ذرة، صوص مكسيكي.', 'موهيتو فريش', 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=700&q=80', 'مكسيكي لذيذ', NULL, true, false, 180),
('mm-25', 'ريفيرا تشيكن (Riviera Chicken)', 'main-meals', 1000, 'دجاج ريفييرا المتوسطي مع صلصة الطماطم المجففة والزيتون والأعشاب والأرز.', 'دجاج مشوي، طماطم مجففة، زيتون كالاماتا، صلصة متوسطية، أرز.', 'عصير ليموناضة', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', NULL, NULL, true, false, 181),
('mm-26', 'فجيتاريا تشيكن (Vegetariana Chicken)', 'main-meals', 1000, 'صدور دجاج مشوية صحية مع تشكيلة واسعة من الخضار السوتيه والأرز البسمتي.', 'صدور دجاج مشوية، بروكلي، كوسا، جزر، فطر، ذرة، أرز بسمتي خفيف.', 'مياه معدنية', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80', 'صحي ومتوازن', ARRAY['gf'], true, false, 182)

ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category_slug = EXCLUDED.category_slug,
    price = EXCLUDED.price,
    description = EXCLUDED.description,
    ingredients = EXCLUDED.ingredients,
    pairing = EXCLUDED.pairing,
    image_url = EXCLUDED.image_url,
    badge = EXCLUDED.badge,
    tags = EXCLUDED.tags,
    is_available = EXCLUDED.is_available,
    is_featured = EXCLUDED.is_featured,
    sort_order = EXCLUDED.sort_order;
